import 'package:get/get.dart';

class Translate extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Enter email address': 'Enter email address',
          'Enter the email': 'Enter the email',
          'Next': 'Next',
          'Login': 'Login',
          'Username': 'Username',
          'Password': 'Password',
          'Forgot password': 'Forgot password?',
          'Continue as guest': 'Continue as guest',
          'Create new account': 'Create new account',
          'Login with facebook': 'Login with facebook',
          'Enter OTP': 'Enter OTP',
          'Enter OTP send to your email': 'Enter OTP send to your email',
          'Resend OTP': 'Resend OTP',
          'Email': 'Email',
          'Country': 'Country',
          'City': 'City',
          'Code': 'Code',
          'Mobile': 'Mobile',
          'Confirm password': 'Confirm password',
          'Create an account': 'Create an account',
          'this field is required': 'this field is required',
          'This field is required': 'This field is required',
          'Reset Password': 'Reset Password',
          'New Password': 'New Password',
          'Confirm Password': 'Confirm Password',
          'Reset Password & Login': 'Reset Password & Login',
          'Ads': 'Ads',
          'Type something...': 'Type something...',
          'Favorites': 'Favorites',
          'Change Language': 'Change Language',
          'Fire Ad': 'Fire Ad',
          'Technical support': 'Technical support',
          'About our market': 'About our market',
          'Politics and Ethics': 'Politics and Ethics',
          'Marketing window': 'Marketing window',
          'Select Country & City': 'Select Country & City',
          'Search': 'Search',
          'Ban': 'Ban',
          'Hide': 'Hide',
          'Report': 'Report',
          'Countries': 'Countries',
          'Cities': 'Cities',
          ' Days ago': ' Days ago',
          'Today': 'Today',
          'Seller: ': 'Seller: ',
          'Edit': 'Edit',
          'Delete': 'Delete',
          'Connect with us': 'Connect with us',
          'Agree': 'Agree',
          'New AD': 'New AD',
          'Select Category': 'Select Category',
          'AD Title': 'AD Title',
          'Price': 'Price',
          'Description': 'Description',
          'Add Images': 'Add Images',
          'Post AD': 'Post AD',
          'Change Password': 'Change Password',
          'Old Password': 'Old Password',
          'Save changes': 'Save changes',
          'Profile': 'Profile',
          'Edit Profile': 'Edit Profile',
          'Logout': 'Logout',
          'Are you sure you want to logout': 'Are you sure you want to logout?',
          'Online': 'Online',
          'My ADs': 'My ADs',
          'Favorite': 'Favorite',
          'Update Profile': 'Update Profile',
          'Full Name': 'Full Name',
          'Camera': 'Camera',
          'Gallery': 'Gallery',
          'Okay': 'Okay',
          'Loading...': 'Loading...',
          'Oops! It took longer to respond.':
              'Oops! It took longer to respond.',
          'Bad Request': 'Bad Request',
          'Unable to process': 'Unable to process',
          'Api not responded in time': 'Api not responded in time',
          'UnAuthorized request': 'UnAuthorized request',
          'No Internet connection': 'No Internet connection',
          'API not responded in time': 'API not responded in time',
          'Error occured with code : ': 'Error occured with code : ',
          //new
          'Soaqna': 'Soaqna',
          'Edit AD': 'Edit AD',
          'Yes': 'Yes',
          'Are you sure you want to permanently delete':
              'Are you sure you want to permanently delete?',
          'Chats': 'Chats',
          'Unauthenticated': 'Unauthenticated',
          'You are using this app as a guest, please login or register':
              'You are using this app as a guest, please login or register',
          'Internet Issue': 'Internet Issue',
          'Yesterday': 'Yesterday',
          'Guest Mode': 'Guest Mode',
          'Trash': 'Trash',
          'Remove': 'Remove',
          'Are you sure you want to remove': 'Are you sure you want to remove',
          'Restore': 'Restore',
          'Are you sure you want to restore':
              'Are you sure you want to restore',
          'No': 'No',
          'Really': 'Really?',
          'Do you want to close the app': 'Do you want to close the app?',
          'Register': 'Register',
          'Filter': 'Filter',
          'By category': 'By category',
          'By city': 'By city',
          'Categories': 'Categories',
          'WhatsApp is not installed on the device':
              'WhatsApp is not installed on the device',
          'packages': 'Packages',
          'I already have an account': 'I already have an account',
          'Or': 'Or'
        },
        'ar_SA': {
          'Enter email address': 'أدخل عنوان البريد الالكتروني',
          'Enter the email': 'أدخل البريد الإلكتروني',
          'Next': 'التالي',
          'Login': 'تسجيل الدخول',
          'Username': 'اسم المستخدم',
          'Password': 'كلمة المرور',
          'Forgot password': 'نسيت كلمة المرور ؟',
          'Continue as guest': 'استمر كضيف',
          'Create new account': 'انشاء حساب جديد',
          'Login with facebook': 'تسجيل الدخول باستخدام الفيسبوك',
          'Enter OTP': 'أدخل رمز التحقق',
          'Enter OTP send to your email':
              'أدخل رمز التحقق أرسل إلى بريدك الإلكتروني',
          'Resend OTP': 'إعادة إرسال رمزالتحقق',
          'Email': 'البريد',
          'Country': 'دولة',
          'City': 'مدينة',
          'Code': 'شفرة',
          'Mobile': 'جوال',
          'Confirm password': 'تأكيد كلمة المرور',
          'Create an account': 'انشئ حساب',
          'this field is required': 'هذه الحقل ضروري',
          'This field is required': 'هذه الخانة ضروري',
          'Reset Password': 'إعادة تعيين كلمة المرور',
          'New Password': 'كلمة المرور الجديدة',
          'Confirm Password': 'تأكيد كلمة المرور',
          'Reset Password & Login': 'إعادة تعيين كلمة المرور وتسجيل الدخول',
          'Ads': 'اعلان',
          'Type something...': 'اطبع شيئا...',
          'Favorites': 'المفضلة',
          'Change Language': 'تغيير اللغه',
          'Fire Ad': 'أعلان الاكثر',
          'Technical support': 'دعم فني',
          'About our market': 'حول سوقنا',
          'Politics and Ethics': 'السياسة والأخلاق',
          'Marketing window': 'نافذة التسويق',
          'Select Country & City': 'حدد الدولة والمدينة',
          'Search': 'يبحث',
          'Ban': 'المنع',
          'Hide': 'يخفي',
          'Report': 'تقرير',
          'Countries': 'الدول',
          'Cities': 'المدينة ',
          ' Days ago': ' أيام مضت',
          'Today': 'اليوم',
          'Seller: ': 'تاجر: ',
          'Edit': 'يحرر',
          'Delete': 'حذف',
          'Connect with us': 'اتصل بنا',
          'Agree': 'يوافق على',
          'New AD': 'إعلان جديد',
          'Select Category': 'اختر الفئة',
          'AD Title': 'عنوان الاعلان',
          'Price': 'سعر',
          'Description': 'وصف',
          'Add Images': 'اضف صورة',
          'Post AD': 'Post AD',
          'Change Password': 'غير كلمة المرور',
          'Old Password': 'كلمة المرور القديمة',
          'Save changes': 'احفظ التغييرات',
          'Profile': 'الملف الشخصي',
          'Edit Profile': 'تعديل الملف الشخصي',
          'Logout': 'تسجيل خروج',
          'Are you sure you want to logout':
              'هل أنت متأكد أنك تريد تسجيل الخروج?',
          'Online': 'ان لاين',
          'My ADs': 'إعلاناتي',
          'Favorite': 'مفضل',
          'Update Profile': 'تحديث الملف',
          'Full Name': 'الاسم الكامل',
          'Camera': 'كاميرا',
          'Gallery': 'استوديو',
          'Okay': 'تمام',
          'Loading...': 'جار التحميل...',
          'Oops! It took longer to respond.':
              'Oops! استغرق الأمر وقتًا أطول للرد.',
          'Bad Request': 'اقتراح غير جيد',
          'Unable to process': 'غير قادر على المعالجة',
          'Api not responded in time': 'Api لم ترد في الوقت المناسب',
          'UnAuthorized request': 'طلب غير مصرح به',
          'No Internet connection': 'لا يوجد اتصال بالإنترنت',
          'API not responded in time': 'API لم تستجب في الوقت المناسب',
          'Error occured with code : ': 'حدث خطأ في الكود : ',
          //new
          'Soaqna': 'سوقنا',
          'Edit AD': 'تحرير م',
          'Yes': 'نعم',
          'Are you sure you want to permanently delete':
              'هل أنت متأكد أنك تريد الحذف نهائيًا',
          'Chats': 'الدردشات',
          'Unauthenticated': 'غير مصدق',
          'You are using this app as a guest, please login or register':
              'نت تستخدم هذا التطبيق كضيف ، يرجى تسجيل الدخول',
          'Internet Issue': 'مشكلة الإنترنت',
          'Yesterday': 'في الامس',
          'Guest Mode': 'وضع الضيف',
          'Trash': 'نفاية',
          'Remove': 'إزالة',
          'Are you sure you want to remove': 'هل أنت متأكد من أنك تريد إزالة',
          'Restore': 'يعيد',
          'Are you sure you want to restore': 'هل أنت متأكد أنك تريد استعادة',
          'No': 'رقم',
          'Really': 'حقًا',
          'Do you want to close the app': 'هل تريد إغلاق التطبيق',
          'Register': 'يسجل',
          'Filter': 'منقي',
          'By category': 'بالتصنيف',
          'By city': 'حسب المدينة',
          'Categories': 'فئات',
          'WhatsApp is not installed on the device':
              'WhatsApp غير مثبت على الجهاز',
          'packages': 'الحزم',
          'I already have an account': "لدي حساب بالفعل",
          'Or': 'او'
        },
      };
}
